sudo: required
cache: false
language: python
services:
- docker
env:
  global:
  - BUILD_DIR=builds
  - secure: "Ri7AXEMu7+B0zV1ptFWwtRZY+6y2w8MUneV+AnAi1qInaaX4FLkA+F1QNpj0vN/r7S8rd+tvkL84HIREDT8GOcQeWfbm/r4I9M1CCIyclRBABZn82W8pJueSDOljxDBUA728L7pL0dDceoTXFHPUELp0b7qbsuVo+RDXxbUg8uUlH3wtBB19fOco8TOGSJulc9JkEbLLH+IPlBv/XKJ+evuLtvrsVZPQnfUQKQ7298Fqyg3OlmmaN8uhpUcgfpsWglrWYZiNd/r8Q5UXiqfI7Y19nudRH1giWVLmhwY9WK1LgtTTx9Pa8ca9racnwefcSWJYEalxyy/9yXhDi3u0abt3OeaQk4eSSiuC6+1GQuW5Mz6+wy26bZ81FUOfVVARs0Ld1zsr9R3NxgdtaAWaPCC7WubD+NT5sWeuB4jlr7Tw0rJMZ4YO32y8KTlqdq2Hwnlf+9IVvlBg8FXoovH2nWa+qrdAtPI3dIUkTRKPdzu8B6m/mcnKAzGsUwQtitfBdL6NUYJYQXZS3ss7A7QlEtdOknQ+EeVjHTJeFtE8VPgYbplElM9NL09wz1Pr2xJiSssKIUyvGuJNX6RHKwNn5VxBKuJmlpH1GVb7/+hgLm0FoU72z8EQdpZL1atU664Ll99iM02wsr/rwe+ZfEA6Lxqh1tTzdQeeuJ7d+MISHjA="
  - secure: "aA/pFr0rMXDd693hx4sOGzHy8TjmrQ4IqS2E3MqHNPnkwtq9PmBlPREOdsf8Al7wp+w6MwJW9xLG7TlJnaPfXDtJSQrY9nsaW/Gg0FnrBMOrQMUNVJevikDZ1JoZFtYWEiW4qr4cMsOP8TAPF0i/5rTFz7+8nWh9+hrDd7ZqafGfvNK84Eq9EW3c52D39F8hVKerKK9qMABks8ZIr2SWwfyIc4MS2LLxpG/8xugNwu8pBF714IJbUqzyCpozqaW+SN5+/SlQixjCEW/PT1RO62l7Th0eisThUke9ISW4wMWkQKmGtMHkdP3LbdKMjOy409Ij3OlvqyGyeIuzON7iluxEKorLe7j0qhYijusH5b/NB2GXkf3VoxxuMjdieKe1wDbmtG9kxaKg6HCGlYv4U6GdDzju03u5wjXm0W0cs1sxBqICADI6CaO6w12RELWcIeLKgHqI+VOkTqfiAHClAJJHL7KB/9JQTHBXcksjhiOsX952lPubvJHMYvSMowfzsq57eJvN2yTJ4pVwe9vRf74Sv+w0tRwTOyVVXFDShUFRMcb7/LeOcQkPuLovY5XhABBQ+NXqFoNA+e5K5LFTaGZSnhfeJHhvNlIqwc7JBspTUS7IQ3734IzLR75xBSi7+ouABf6ZYu3G1PrgE6q4IOROqRrOq0kLnevU5+nDcLc="
  matrix:
  - IMAGE_NAME=python_2.7
  - IMAGE_NAME=python_3.5
  - IMAGE_NAME=python_3.6
  - IMAGE_NAME=pypy_2
  - IMAGE_NAME=pypy_3
  - IMAGE_NAME=anaconda_2
  - IMAGE_NAME=anaconda_3
script:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - docker build --no-cache --pull -t ${IMAGE_NAME} ${BUILD_DIR}/${IMAGE_NAME}
  - docker tag ${IMAGE_NAME} $DOCKERHUB_USER/${IMAGE_NAME}
  - docker push ${IMAGE_NAME} $DOCKERHUB_USER/${IMAGE_NAME}
